vich_uploader:
    db_driver: orm

    mappings:
       produit:
           uri_prefix: /images/produit
           upload_destination: '%kernel.project_dir%/public/images/produit'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
