vich_uploader:
    db_driver: orm

    mappings:
        produit:
           uri_prefix: /image/produit
           upload_destination: '%kernel.project_dir%/public/image/produit'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer 

